name: hrm_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  dropdown_button2: ^1.9.2
  image_picker: ^0.8.7+5
  pin_code_fields: ^7.4.0
  country_list_pick: ^1.0.1+6
  flutter_neat_and_clean_calendar: ^0.3.13+28
  getwidget: ^3.1.1
  intl: any
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.1.0
  flutter_html: ^2.2.1
  cached_network_image: ^3.2.3
  table_calendar: ^3.0.9
  onesignal_flutter: ^3.5.1
  badges: ^3.1.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  searchfield: ^0.8.3
  file_picker: ^5.2.10
  flutter_file_downloader: ^1.1.2
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  open_file: ^3.3.2
  permission_handler: ^10.4.2
  url_launcher: ^6.1.11
  photo_view: ^0.14.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: poppins
      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
